### **LIBRARIES**

In [1]:
import os           # os.path.join
import numpy as np  # np.concatenate
import pandas as pd

import bow
import utils

#pd.get_dummies

from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer  # fit_transform

[nltk_data] Downloading package stopwords to /home/ronkow/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


### **GLOBAL CONSTANTS, DATA**

In [2]:
DATA_DIR = "data/"

### **ONE HOT ENCODE THE TESTING DATA (NO TARGET LABELS)**

In [3]:
DATA_FILE_TEXT = os.path.join(DATA_DIR, "test_text.csv")           
DATA_FILE_KEYWORD = os.path.join(DATA_DIR, "test_keyword.csv")
DATA_FILE_TARGET = os.path.join(DATA_DIR, "test_target.csv")

In [4]:
# USE LARGEST SET OF BAG OF WORDS (2944 TERMS)

token_list = utils.csv_to_list_of_strings('data/tokens/train_text_token4.csv')
print(token_list[0:10])
print(len(token_list))
print('')

keyword_list = utils.csv_to_list_of_strings('data/bow/train_bow_keyword.csv')
print(keyword_list[0:10])
print(len(keyword_list))

['reason', '#earthquak', 'may', 'allah', 'us', 'forest', 'fire', 'near', 'la', 'canada']
2944

['kw_ablaze', 'kw_accident', 'kw_aftershock', 'kw_airplaneaccident', 'kw_ambulance', 'kw_annihilated', 'kw_annihilation', 'kw_apocalypse', 'kw_armageddon', 'kw_army']
222


In [5]:
text_list = utils.csv_to_list_of_strings(DATA_FILE_TEXT)
print(text_list[0:3])
print('')

text_token_list1 = bow.list_of_token_lists_text(text_list, token_list)
print(text_token_list1[0:3])
print(len(text_token_list1))
print('')

token_list1 = [token_list]
text_token_list = token_list1 + text_token_list1 
print(text_token_list[1:3])
print(len(text_token_list))


['Just happened a terrible car crash', 'Heard about #earthquake is different cities, stay safe everyone.', 'there is a forest fire at spot pond, geese are fleeing across the street, I cannot save them all']

[['happen', 'terribl', 'car', 'crash'], ['heard', '#earthquak', 'differ', 'citi', 'stay', 'safe', 'everyon'], ['forest', 'fire', 'spot', 'pond', 'across', 'street', 'cannot', 'save']]
3263

[['happen', 'terribl', 'car', 'crash'], ['heard', '#earthquak', 'differ', 'citi', 'stay', 'safe', 'everyon']]
3264


In [11]:
onehot_multi_text = MultiLabelBinarizer()

onehot_text_nolabel = onehot_multi_text.fit_transform(text_token_list)
num_row, num_col = onehot_text_nolabel.shape

print(onehot_text_nolabel)
print(onehot_text_nolabel.shape)
print('')

onehot_text_nolabel = np.delete(onehot_text_nolabel, (0), axis=0)
print(onehot_text_nolabel)
print(onehot_text_nolabel.shape)
print('')

text_labels = onehot_multi_text.classes_
text_labels = text_labels.reshape(1, num_col)

print(text_labels)
print(text_labels.shape)
print('')

onehot_text = np.concatenate((text_labels,onehot_text_nolabel), axis=0)
print(onehot_text)
print(onehot_text.shape)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3264, 2944)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3263, 2944)

[['#1' '#360wisenew' '#7' ... '\x89û÷polit' 'åè' 'åê']]
(1, 2944)

[['#1' '#360wisenew' '#7' ... '\x89û÷polit' 'åè' 'åê']
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3264, 2944)


In [12]:
keyword_list = utils.csv_to_list_of_strings(DATA_FILE_KEYWORD)
print(keyword_list[0:10])
print('')

keyword_token_list = bow.list_of_token_lists_keyword(keyword_list)
print(keyword_token_list[0:10])
print(len(keyword_token_list))

['crash', 'earthquake', 'forestfire', 'wildfires', 'typhoon', 'earthquake', 'na', 'na', 'na', 'na']

[['kw_crash'], ['kw_earthquake'], ['kw_forestfire'], ['kw_wildfires'], ['kw_typhoon'], ['kw_earthquake'], ['kw_na'], ['kw_na'], ['kw_na'], ['kw_na']]
3263


In [13]:
onehot_multi_keyword = MultiLabelBinarizer()
onehot_keyword_nolabel = onehot_multi_keyword.fit_transform(keyword_token_list)
num_row, num_col = onehot_keyword_nolabel.shape

print(onehot_keyword_nolabel)
print(onehot_keyword_nolabel.shape)
print('')

keyword_labels = onehot_multi_keyword.classes_
keyword_labels = keyword_labels.reshape(1, num_col)

print(keyword_labels)
print(keyword_labels.shape)
print('')

onehot_keyword = np.concatenate((keyword_labels,onehot_keyword_nolabel), axis=0)
print(onehot_keyword)
print(onehot_keyword.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3263, 222)

[['kw_ablaze' 'kw_accident' 'kw_aftershock' 'kw_airplaneaccident'
  'kw_ambulance' 'kw_annihilated' 'kw_annihilation' 'kw_apocalypse'
  'kw_armageddon' 'kw_army' 'kw_arson' 'kw_arsonist' 'kw_attack'
  'kw_attacked' 'kw_avalanche' 'kw_battle' 'kw_bioterror'
  'kw_bioterrorism' 'kw_blaze' 'kw_blazing' 'kw_bleeding' 'kw_blewup'
  'kw_blight' 'kw_blizzard' 'kw_blood' 'kw_bloody' 'kw_blownup'
  'kw_bodybag' 'kw_bodybagging' 'kw_bodybags' 'kw_bomb' 'kw_bombed'
  'kw_bombing' 'kw_bridgecollapse' 'kw_buildingsburning'
  'kw_buildingsonfire' 'kw_burned' 'kw_burning' 'kw_burningbuildings'
  'kw_bushfires' 'kw_casualties' 'kw_casualty' 'kw_catastrophe'
  'kw_catastrophic' 'kw_chemicalemergency' 'kw_clifffall' 'kw_collapse'
  'kw_collapsed' 'kw_collide' 'kw_collided' 'kw_collision' 'kw_crash'
  'kw_crashed' 'kw_crush' 'kw_crushed' 'kw_curfew' 'kw_cyclone'
  'kw_damag

In [15]:
onehot_test = np.concatenate((onehot_keyword,onehot_text), axis=1)
print(onehot_test)
print(onehot_test.shape)

[['kw_ablaze' 'kw_accident' 'kw_aftershock' ... '\x89û÷polit' 'åè' 'åê']
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3264, 3166)


In [18]:
test_df = utils.np_array_to_dataframe(onehot_test)
test_df

kw_ablaze kw_accident kw_aftershock kw_airplaneaccident kw_ambulance  \
0            0           0             0                   0            0   
1            0           0             0                   0            0   
2            0           0             0                   0            0   
3            0           0             0                   0            0   
4            0           0             0                   0            0   
...        ...         ...           ...                 ...          ...   
3258         0           0             0                   0            0   
3259         0           0             0                   0            0   
3260         0           0             0                   0            0   
3261         0           0             0                   0            0   
3262         0           0             0                   0            0   

     kw_annihilated kw_annihilation kw_apocalypse kw_armageddon kw_army  ...  \
0                 0               0             0             0       0  ...   
1                 0               0             0             0       0  ...   
2                 0               0             0             0       0  ...   
3                 0               0             0             0       0  ...   
4                 0               0             0             0       0  ...   
...             ...             ...           ...           ...     ...  ...   
3258              0               0             0             0       0  ...   
3259              0               0             0             0       0  ...   
3260              0               0             0             0       0  ...   
3261              0               0             0             0       0  ...   
3262              0               0             0             0       0  ...   

     ‰ûïa ‰ûïthe ‰ûïwe ‰ûïwhen ‰ûò ‰ûó ‰û÷extrem ‰û÷polit åè åê  
0       0      0     0       0   0   0         0        0  0  0  
1       0      0     0       0   0   0         0        0  0  0  
2       0      0     0       0   0   0         0        0  0  0  
3       0      0     0       0   0   0         0        0  0  0  
4       0      0     0       0   0   0         0        0  0  0  
...   ...    ...   ...     ...  ..  ..       ...      ... .. ..  
3258    0      0     0       0   1   0         0        0  0  0  
3259    0      0     0       0   0   0         0        0  0  0  
3260    0      0     0       0   0   0         0        0  0  0  
3261    0      0     0       0   0   0         0        0  0  0  
3262    0      0     0       0   0   0         0        0  0  0  

[3263 rows x 3166 columns]

In [19]:
DATA_FILE_BOW = os.path.join(DATA_DIR, "bow/test_bow.csv")

utils.dataframe_to_csv(test_df, DATA_FILE_BOW)