### **LIBRARIES**

In [1]:
import os           # os.path.join
import numpy as np  # np.concatenate
import pandas as pd

import bow
import utils

#pd.get_dummies

from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer  # fit_transform

[nltk_data] Downloading package stopwords to /home/ronkow/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


### **GLOBAL CONSTANTS, DATA**

In [2]:
DATA_DIR = "data/"

### **ONE HOT ENCODE THE COMPLETE TRAINING DATASET**

In [3]:
DATA_FILE_TEXT = os.path.join(DATA_DIR, "train_text.csv")           
DATA_FILE_KEYWORD = os.path.join(DATA_DIR, "train_keyword.csv")
DATA_FILE_TARGET = os.path.join(DATA_DIR, "train_target.csv")

In [4]:
# USE LARGEST SET OF BAG OF WORDS (2944 TERMS)

token_list = utils.csv_to_list_of_strings('data/tokens/train_text_token4.csv')
print(token_list[0:10])
print('')

text_list = utils.csv_to_list_of_strings(DATA_FILE_TEXT)
print(text_list[0:3])
print('')

text_token_list = bow.list_of_token_lists_text(text_list, token_list)
print(text_token_list[0:3])


['reason', '#earthquak', 'may', 'allah', 'us', 'forest', 'fire', 'near', 'la', 'canada']

['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all', 'Forest fire near La Ronge Sask. Canada', "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected"]

[['reason', '#earthquak', 'may', 'allah', 'us'], ['forest', 'fire', 'near', 'la', 'canada'], ['resid', 'ask', 'shelter', 'place', 'offic', 'evacu', 'shelter', 'place', 'order', 'expect']]


In [6]:
onehot_multi_text = MultiLabelBinarizer()

onehot_text_nolabel = onehot_multi_text.fit_transform(text_token_list)
num_row, num_col = onehot_text_nolabel.shape

print(onehot_text_nolabel)
print(onehot_text_nolabel.shape)
print('')

text_labels = onehot_multi_text.classes_
text_labels = text_labels.reshape(1, num_col)

print(text_labels)
print(text_labels.shape)
print('')

onehot_text = np.concatenate((text_labels,onehot_text_nolabel), axis=0)
print(onehot_text)
print(onehot_text.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(7613, 2944)

[['#1' '#360wisenew' '#7' ... '\x89û÷polit' 'åè' 'åê']]
(1, 2944)

[['#1' '#360wisenew' '#7' ... '\x89û÷polit' 'åè' 'åê']
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(7614, 2944)


In [7]:
keyword_list = utils.csv_to_list_of_strings(DATA_FILE_KEYWORD)
print(keyword_list[0:10])
print('')

keyword_token_list = bow.list_of_token_lists_keyword(keyword_list)
print(keyword_token_list[0:10])

['earthquake', 'forestfire', 'evacuation', 'wildfires', 'wildfires', 'wildfires', 'flood', 'fire', 'evacuation', 'tornado']

[['kw_earthquake'], ['kw_forestfire'], ['kw_evacuation'], ['kw_wildfires'], ['kw_wildfires'], ['kw_wildfires'], ['kw_flood'], ['kw_fire'], ['kw_evacuation'], ['kw_tornado']]


In [8]:
onehot_multi_keyword = MultiLabelBinarizer()
onehot_keyword_nolabel = onehot_multi_keyword.fit_transform(keyword_token_list)
num_row, num_col = onehot_keyword_nolabel.shape

print(onehot_keyword_nolabel)
print(onehot_keyword_nolabel.shape)
print('')

keyword_labels = onehot_multi_keyword.classes_
keyword_labels = keyword_labels.reshape(1, num_col)

print(keyword_labels)
print(keyword_labels.shape)
print('')

onehot_keyword = np.concatenate((keyword_labels,onehot_keyword_nolabel), axis=0)
print(onehot_keyword)
print(onehot_keyword.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(7613, 222)

[['kw_ablaze' 'kw_accident' 'kw_aftershock' 'kw_airplaneaccident'
  'kw_ambulance' 'kw_annihilated' 'kw_annihilation' 'kw_apocalypse'
  'kw_armageddon' 'kw_army' 'kw_arson' 'kw_arsonist' 'kw_attack'
  'kw_attacked' 'kw_avalanche' 'kw_battle' 'kw_bioterror'
  'kw_bioterrorism' 'kw_blaze' 'kw_blazing' 'kw_bleeding' 'kw_blewup'
  'kw_blight' 'kw_blizzard' 'kw_blood' 'kw_bloody' 'kw_blownup'
  'kw_bodybag' 'kw_bodybagging' 'kw_bodybags' 'kw_bomb' 'kw_bombed'
  'kw_bombing' 'kw_bridgecollapse' 'kw_buildingsburning'
  'kw_buildingsonfire' 'kw_burned' 'kw_burning' 'kw_burningbuildings'
  'kw_bushfires' 'kw_casualties' 'kw_casualty' 'kw_catastrophe'
  'kw_catastrophic' 'kw_chemicalemergency' 'kw_clifffall' 'kw_collapse'
  'kw_collapsed' 'kw_collide' 'kw_collided' 'kw_collision' 'kw_crash'
  'kw_crashed' 'kw_crush' 'kw_crushed' 'kw_curfew' 'kw_cyclone'
  'kw_damag

In [9]:
onehot_train = np.concatenate((onehot_keyword,onehot_text), axis=1)
print(onehot_train)
print(onehot_train.shape)

[['kw_ablaze' 'kw_accident' 'kw_aftershock' ... '\x89û÷polit' 'åè' 'åê']
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(7614, 3166)


In [10]:
train_df = utils.np_array_to_dataframe(onehot_train)
train_df

kw_ablaze kw_accident kw_aftershock kw_airplaneaccident kw_ambulance  \
0            0           0             0                   0            0   
1            0           0             0                   0            0   
2            0           0             0                   0            0   
3            0           0             0                   0            0   
4            0           0             0                   0            0   
...        ...         ...           ...                 ...          ...   
7608         0           0             0                   0            0   
7609         0           0             0                   0            0   
7610         0           0             0                   0            0   
7611         0           0             0                   0            0   
7612         0           0             0                   0            0   

     kw_annihilated kw_annihilation kw_apocalypse kw_armageddon kw_army  ...  \
0                 0               0             0             0       0  ...   
1                 0               0             0             0       0  ...   
2                 0               0             0             0       0  ...   
3                 0               0             0             0       0  ...   
4                 0               0             0             0       0  ...   
...             ...             ...           ...           ...     ...  ...   
7608              0               0             0             0       0  ...   
7609              0               0             0             0       0  ...   
7610              0               0             0             0       0  ...   
7611              0               0             0             0       0  ...   
7612              0               0             0             0       0  ...   

     ‰ûïa ‰ûïthe ‰ûïwe ‰ûïwhen ‰ûò ‰ûó ‰û÷extrem ‰û÷polit åè åê  
0       0      0     0       0   0   0         0        0  0  0  
1       0      0     0       0   0   0         0        0  0  0  
2       0      0     0       0   0   0         0        0  0  0  
3       0      0     0       0   0   0         0        0  0  0  
4       0      0     0       0   0   0         0        0  0  0  
...   ...    ...   ...     ...  ..  ..       ...      ... .. ..  
7608    0      0     0       0   0   0         0        0  0  0  
7609    0      0     0       0   0   0         0        0  0  0  
7610    0      0     0       0   0   0         0        0  0  0  
7611    0      0     0       0   0   0         0        0  0  0  
7612    0      0     0       0   0   0         0        0  0  0  

[7613 rows x 3166 columns]

### **APPEND TARGET COLUMN TO TRAINING SET**

In [11]:
train_target = utils.csv_to_dataframe(DATA_FILE_TARGET)
train_target

target
0          1
1          1
2          1
3          1
4          1
...      ...
7608       1
7609       1
7610       1
7611       1
7612       1

[7613 rows x 1 columns]

In [12]:
train_df_with_target = pd.concat([train_df, train_target], axis=1)
train_df_with_target

kw_ablaze kw_accident kw_aftershock kw_airplaneaccident kw_ambulance  \
0            0           0             0                   0            0   
1            0           0             0                   0            0   
2            0           0             0                   0            0   
3            0           0             0                   0            0   
4            0           0             0                   0            0   
...        ...         ...           ...                 ...          ...   
7608         0           0             0                   0            0   
7609         0           0             0                   0            0   
7610         0           0             0                   0            0   
7611         0           0             0                   0            0   
7612         0           0             0                   0            0   

     kw_annihilated kw_annihilation kw_apocalypse kw_armageddon kw_army  ...  \
0                 0               0             0             0       0  ...   
1                 0               0             0             0       0  ...   
2                 0               0             0             0       0  ...   
3                 0               0             0             0       0  ...   
4                 0               0             0             0       0  ...   
...             ...             ...           ...           ...     ...  ...   
7608              0               0             0             0       0  ...   
7609              0               0             0             0       0  ...   
7610              0               0             0             0       0  ...   
7611              0               0             0             0       0  ...   
7612              0               0             0             0       0  ...   

     ‰ûïthe ‰ûïwe ‰ûïwhen ‰ûò ‰ûó ‰û÷extrem ‰û÷polit åè åê target  
0         0     0       0   0   0         0        0  0  0      1  
1         0     0       0   0   0         0        0  0  0      1  
2         0     0       0   0   0         0        0  0  0      1  
3         0     0       0   0   0         0        0  0  0      1  
4         0     0       0   0   0         0        0  0  0      1  
...     ...   ...     ...  ..  ..       ...      ... .. ..    ...  
7608      0     0       0   0   0         0        0  0  0      1  
7609      0     0       0   0   0         0        0  0  0      1  
7610      0     0       0   0   0         0        0  0  0      1  
7611      0     0       0   0   0         0        0  0  0      1  
7612      0     0       0   0   0         0        0  0  0      1  

[7613 rows x 3167 columns]

### **CONVERT DATAFRAME TO CSV FILE**

In [13]:
DATA_FILE_BOW = os.path.join(DATA_DIR, "bow/train_bow.csv")

utils.dataframe_to_csv(train_df_with_target, DATA_FILE_BOW)

### **SAVE KEYWORD LABELS AS CSV FILE (needed when we one-hot encode the test data)**

In [14]:
#keyword_labels = keyword_labels.reshape(0, num_col)

keyword_labels = onehot_multi_keyword.classes_
print(keyword_labels.shape)
print(keyword_labels[0:10])


(222,)
['kw_ablaze' 'kw_accident' 'kw_aftershock' 'kw_airplaneaccident'
 'kw_ambulance' 'kw_annihilated' 'kw_annihilation' 'kw_apocalypse'
 'kw_armageddon' 'kw_army']


In [15]:
def list_to_csv(list, filepath):
    """
    ARGUMENT: list, file path
    RETURN: csv file
    Convert to dataframe first, then convert dataframe to csv file
    """
    #df = pd.DataFrame(list, columns=["text_tokens"])
    df = pd.DataFrame(list)
    df.to_csv(filepath, index=False)

In [16]:
DATA_FILE_BOW_KEYWORD = os.path.join(DATA_DIR, "bow/train_bow_keyword.csv")

list_to_csv(keyword_labels, DATA_FILE_BOW_KEYWORD)