### **LIBRARIES**

In [1]:
import os           # os.path.join
import numpy as np  # np.concatenate
import pandas as pd

import bow
import utils

#pd.get_dummies

from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer  # fit_transform

[nltk_data] Downloading package stopwords to /home/ronkow/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


### **GLOBAL CONSTANTS, DATA**

In [3]:
# train_text9.csv, train_keyword9.csv are SMALL DATASETS used to test the code

DATA_DIR = "data/"

DATA_FILE_TEXT = os.path.join(DATA_DIR, "datasets_small/train_text9.csv")           
DATA_FILE_KEYWORD = os.path.join(DATA_DIR, "datasets_small/train_keyword9.csv")

### **(1) ONE HOT ENCODE TEXT** (TEST THE CODE USING SMALL DATASET)
### **EXPLORE DATA**

In [3]:
# CHECK
s = utils.file_to_string(DATA_FILE_TEXT)
print(s)

text_list1 = utils.csv_to_list_of_lists(DATA_FILE_TEXT)
print(text_list1)

"text"
"Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all"
"Forest fire near La Ronge Sask. Canada"
"All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected"
"13,000 people receive #wildfires evacuation orders in California "
"Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school"
"#RockyFire Update => California Hwy. 20 closed in both directions due to Lake County fire - #CAfire #wildfires"
"#flood #disaster Heavy rain causes flash flooding of streets in Manitou, Colorado Springs areas"
"I'm on top of the hill and I can see a fire in the woods..."
"There's an emergency evacuation happening now in the building across the street"

[['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'], ['Forest fire near La Ronge Sask. Canada'], ["All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in 

### **RUN**

In [4]:
token_list = utils.csv_to_list_of_strings('data/tokens/train_text_token100.csv')
print(token_list[0:20])
print('')

text_list = utils.csv_to_list_of_strings(DATA_FILE_TEXT)
print(text_list)
print('')

text_token_list = bow.list_of_token_lists_text(text_list, token_list)
print(text_token_list)

['us', 'fire', 'evacu', 'peopl', 'california', 'got', 'caus', 'flood', 'see', 'emerg', 'build', 'come', 'get', 'live', 'day', 'car', 'crash', 'man', 'love', 'like']

['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all', 'Forest fire near La Ronge Sask. Canada', "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected", '13,000 people receive #wildfires evacuation orders in California ', 'Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school', '#RockyFire Update => California Hwy. 20 closed in both directions due to Lake County fire - #CAfire #wildfires', '#flood #disaster Heavy rain causes flash flooding of streets in Manitou, Colorado Springs areas', "I'm on top of the hill and I can see a fire in the woods...", "There's an emergency evacuation happening now in the building across the street"]

[['us'], ['fire'], ['evacu'], ['peopl', 'evacu', 'california'

In [5]:
onehot_multi_text = MultiLabelBinarizer()

onehot_text_nolabel = onehot_multi_text.fit_transform(text_token_list)
num_row, num_col = onehot_text_nolabel.shape

print(onehot_text_nolabel)
print(onehot_text_nolabel.shape)
#print(type(onehot_text_nolabel))
print('')

text_labels = onehot_multi_text.classes_
text_labels = text_labels.reshape(1, num_col)

print(text_labels)
print(text_labels.shape)
#print(type(text_labels))
print('')

onehot_text = np.concatenate((text_labels,onehot_text_nolabel), axis=0)
print(onehot_text)
print(onehot_text.shape)

[[0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0]
 [1 0 0 1 1 0 0 0 0 0 0]]
(9, 11)

[['build' 'california' 'caus' 'emerg' 'evacu' 'fire' 'flood' 'got'
  'peopl' 'see' 'us']]
(1, 11)

[['build' 'california' 'caus' 'emerg' 'evacu' 'fire' 'flood' 'got'
  'peopl' 'see' 'us']
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0]
 [1 0 0 1 1 0 0 0 0 0 0]]
(10, 11)


### **ONE HOT ENCODE KEYWORDS** (USING SMALL DATASET)  
### **EXPLORE DATA** 

In [6]:
# CHECK

s = utils.file_to_string(DATA_FILE_KEYWORD)
print(s)
print('')

keyword_list1 = bow.clean_doc_keyword(s)
print(keyword_list1)

"keyword"
"earthquake"
"forestfire"
"evacuation"
"wildfires"
"wildfires"
"wildfires"
"flood"
"fire"
"evacuation"


['kw_keyword', 'kw_earthquake', 'kw_forestfire', 'kw_evacuation', 'kw_wildfires', 'kw_wildfires', 'kw_wildfires', 'kw_flood', 'kw_fire', 'kw_evacuation']


### **RUN**

In [7]:
keyword_list = utils.csv_to_list_of_strings(DATA_FILE_KEYWORD)
print(keyword_list)
print('')

keyword_token_list = bow.list_of_token_lists_keyword(keyword_list)
print(keyword_token_list)

['earthquake', 'forestfire', 'evacuation', 'wildfires', 'wildfires', 'wildfires', 'flood', 'fire', 'evacuation']

[['kw_earthquake'], ['kw_forestfire'], ['kw_evacuation'], ['kw_wildfires'], ['kw_wildfires'], ['kw_wildfires'], ['kw_flood'], ['kw_fire'], ['kw_evacuation']]


In [8]:
onehot_multi_keyword = MultiLabelBinarizer()
onehot_keyword_nolabel = onehot_multi_keyword.fit_transform(keyword_token_list)
num_row, num_col = onehot_keyword_nolabel.shape

print(onehot_keyword_nolabel)
print(onehot_keyword_nolabel.shape)
#print(type(onehot_keyword_nolabel))
print('')

keyword_labels = onehot_multi_keyword.classes_
keyword_labels = keyword_labels.reshape(1, num_col)

print(keyword_labels)
print(keyword_labels.shape)
#print(type(keyword_labels))
print('')

onehot_keyword = np.concatenate((keyword_labels,onehot_keyword_nolabel), axis=0)
print(onehot_keyword)
print(onehot_keyword.shape)

[[1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]]
(9, 6)

[['kw_earthquake' 'kw_evacuation' 'kw_fire' 'kw_flood' 'kw_forestfire'
  'kw_wildfires']]
(1, 6)

[['kw_earthquake' 'kw_evacuation' 'kw_fire' 'kw_flood' 'kw_forestfire'
  'kw_wildfires']
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]]
(10, 6)


### **CONCATENATE KEYWORD AND TEXT ONE HOT DATA**

In [9]:
onehot_train = np.concatenate((onehot_keyword,onehot_text), axis=1)
print(onehot_train)
print(onehot_train.shape)

[['kw_earthquake' 'kw_evacuation' 'kw_fire' 'kw_flood' 'kw_forestfire'
  'kw_wildfires' 'build' 'california' 'caus' 'emerg' 'evacu' 'fire'
  'flood' 'got' 'peopl' 'see' 'us']
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0]]
(10, 17)


### **CONVERT NUMPY ARRAY TO DATAFRAME**

In [10]:
train_df = utils.np_array_to_dataframe(onehot_train)
train_df

kw_earthquake kw_evacuation kw_fire kw_flood kw_forestfire kw_wildfires  \
0             1             0       0        0             0            0   
1             0             0       0        0             1            0   
2             0             1       0        0             0            0   
3             0             0       0        0             0            1   
4             0             0       0        0             0            1   
5             0             0       0        0             0            1   
6             0             0       0        1             0            0   
7             0             0       1        0             0            0   
8             0             1       0        0             0            0   

  build california caus emerg evacu fire flood got peopl see us  
0     0          0    0     0     0    0     0   0     0   0  1  
1     0          0    0     0     0    1     0   0     0   0  0  
2     0          0    0     0     1    0     0   0     0   0  0  
3     0          1    0     0     1    0     0   0     1   0  0  
4     0          0    0     0     0    0     0   1     0   0  0  
5     0          1    0     0     0    1     0   0     0   0  0  
6     0          0    1     0     0    0     1   0     0   0  0  
7     0          0    0     0     0    1     0   0     0   1  0  
8     1          0    0     1     1    0     0   0     0   0  0

In [11]:
DATA_FILE_BOW = os.path.join(DATA_DIR, "bow/train_bow9.csv")

utils.dataframe_to_csv(train_df, DATA_FILE_BOW)