### **LIBRARIES**

In [27]:
import os           # os.path.join
import numpy as np  # np.concatenate
import pandas as pd

import bow
import utils

#pd.get_dummies

from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer  # fit_transform

### **GLOBAL CONSTANTS, DATA**

In [28]:
DATA_DIR = "data/"

### **ONE HOT ENCODE THE TESTING DATA (NO TARGET LABELS)**

In [17]:
DATA_FILE_TEXT = os.path.join(DATA_DIR, "test_text.csv")           
DATA_FILE_KEYWORD = os.path.join(DATA_DIR, "test_keyword.csv")
DATA_FILE_TARGET = os.path.join(DATA_DIR, "test_target.csv")

In [29]:
# USE LARGEST SET OF BAG OF WORDS

token_list = utils.csv_to_list_of_strings('data/tokensfinal/train_text_token10hashuser3.csv')
print(token_list[0:10])
print(len(token_list))
print('')

keyword_list = utils.csv_to_list_of_strings('data/bowfinal10/train_bow_keyword.csv')
print(keyword_list[0:10])
print(len(keyword_list))

['reason', '#earthquak', 'may', 'us', 'forest', 'fire', 'near', 'la', 'canada', 'ask']
1608

['kw_ablaze', 'kw_accident', 'kw_aftershock', 'kw_airplaneaccident', 'kw_ambulance', 'kw_annihilated', 'kw_annihilation', 'kw_apocalypse', 'kw_armageddon', 'kw_army']
222


In [30]:
text_list = utils.csv_to_list_of_strings(DATA_FILE_TEXT)
print(text_list[0:3])
print('')

text_token_list1 = bow.list_of_token_lists_text(text_list, token_list)
print(text_token_list1[0:3])
print(len(text_token_list1))
print('')

token_list1 = [token_list]
text_token_list = token_list1 + text_token_list1 
print(text_token_list[1:3])
print(len(text_token_list))


['Just happened a terrible car crash', 'Heard about #earthquake is different cities, stay safe everyone.', 'there is a forest fire at spot pond, geese are fleeing across the street, I cannot save them all']

[['happen', 'car', 'crash'], ['heard', '#earthquak', 'differ', 'citi', 'stay', 'safe', 'everyon'], ['forest', 'fire', 'spot', 'across', 'street', 'cannot', 'save']]
3263

[['happen', 'car', 'crash'], ['heard', '#earthquak', 'differ', 'citi', 'stay', 'safe', 'everyon']]
3264


In [31]:
onehot_multi_text = MultiLabelBinarizer()

onehot_text_nolabel = onehot_multi_text.fit_transform(text_token_list)
num_row, num_col = onehot_text_nolabel.shape

print(onehot_text_nolabel)
print(onehot_text_nolabel.shape)
print('')

onehot_text_nolabel = np.delete(onehot_text_nolabel, (0), axis=0)
print(onehot_text_nolabel)
print(onehot_text_nolabel.shape)
print('')

text_labels = onehot_multi_text.classes_
text_labels = text_labels.reshape(1, num_col)

print(text_labels)
print(text_labels.shape)
print('')

onehot_text = np.concatenate((text_labels,onehot_text_nolabel), axis=0)
print(onehot_text)
print(onehot_text.shape)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3264, 1608)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3263, 1608)

[['#1' '#360wisenew' '#7' ... '\x89ûïwhen' '\x89ûò' '\x89ûó']]
(1, 1608)

[['#1' '#360wisenew' '#7' ... '\x89ûïwhen' '\x89ûò' '\x89ûó']
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3264, 1608)


In [32]:
'''
text_list = utils.csv_to_list_of_strings(DATA_FILE_TEXT)
print(text_list[0:3])
print('')

text_token_list1 = bow.list_of_token_lists_text(text_list, token_list)
print(text_token_list1[0:3])
print(len(text_token_list1))
print('')

token_list1 = [token_list]
text_token_list = token_list1 + text_token_list1 
print(text_token_list[1:3])
print(len(text_token_list))
'''



keyword_list_test = utils.csv_to_list_of_strings(DATA_FILE_KEYWORD)
print(keyword_list_test[0:10])
print(len(keyword_list_test))
print('')


keyword_token_list1 = bow.list_of_token_lists_keyword(keyword_list_test)
print(keyword_token_list1[0:10])
print(len(keyword_token_list1))
print('')

keyword_list1 = [keyword_list]
print(len(keyword_list))
print(len(keyword_list1))
print('')

keyword_token_list = keyword_list1 + keyword_token_list1 
print(keyword_token_list[1:3])
print(len(keyword_token_list))



['crash', 'earthquake', 'forestfire', 'wildfires', 'typhoon', 'earthquake', 'na', 'na', 'na', 'na']
3263

[['kw_crash'], ['kw_earthquake'], ['kw_forestfire'], ['kw_wildfires'], ['kw_typhoon'], ['kw_earthquake'], ['kw_na'], ['kw_na'], ['kw_na'], ['kw_na']]
3263

222
1

[['kw_crash'], ['kw_earthquake']]
3264


In [33]:
onehot_multi_keyword = MultiLabelBinarizer()
onehot_keyword_nolabel = onehot_multi_keyword.fit_transform(keyword_token_list)
num_row, num_col = onehot_keyword_nolabel.shape

print(onehot_keyword_nolabel)
print(onehot_keyword_nolabel.shape)
print('')


onehot_keyword_nolabel = np.delete(onehot_keyword_nolabel, (0), axis=0)
print(onehot_keyword_nolabel)
print(onehot_keyword_nolabel.shape)
print('')

keyword_labels = onehot_multi_keyword.classes_
keyword_labels = keyword_labels.reshape(1, num_col)

print(keyword_labels)
print(keyword_labels.shape)
print('')

onehot_keyword = np.concatenate((keyword_labels,onehot_keyword_nolabel), axis=0)
print(onehot_keyword)
print(onehot_keyword.shape)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3264, 222)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3263, 222)

[['kw_ablaze' 'kw_accident' 'kw_aftershock' 'kw_airplaneaccident'
  'kw_ambulance' 'kw_annihilated' 'kw_annihilation' 'kw_apocalypse'
  'kw_armageddon' 'kw_army' 'kw_arson' 'kw_arsonist' 'kw_attack'
  'kw_attacked' 'kw_avalanche' 'kw_battle' 'kw_bioterror'
  'kw_bioterrorism' 'kw_blaze' 'kw_blazing' 'kw_bleeding' 'kw_blewup'
  'kw_blight' 'kw_blizzard' 'kw_blood' 'kw_bloody' 'kw_blownup'
  'kw_bodybag' 'kw_bodybagging' 'kw_bodybags' 'kw_bomb' 'kw_bombed'
  'kw_bombing' 'kw_bridgecollapse' 'kw_buildingsburning'
  'kw_buildingsonfire' 'kw_burned' 'kw_burning' 'kw_burningbuildings'
  'kw_bushfires' 'kw_casualties' 'kw_casualty' 'kw_catastrophe'
  'kw_catastrophic' 'kw_chemicalemergency' 'kw_clifffall' 'kw_collapse'
  'kw_collap

In [34]:
onehot_test = np.concatenate((onehot_keyword,onehot_text), axis=1)
print(onehot_test)
print(onehot_test.shape)

[['kw_ablaze' 'kw_accident' 'kw_aftershock' ... '\x89ûïwhen' '\x89ûò'
  '\x89ûó']
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3264, 1830)


In [35]:
test_df = utils.np_array_to_dataframe(onehot_test)
test_df

kw_ablaze kw_accident kw_aftershock kw_airplaneaccident kw_ambulance  \
0            0           0             0                   0            0   
1            0           0             0                   0            0   
2            0           0             0                   0            0   
3            0           0             0                   0            0   
4            0           0             0                   0            0   
...        ...         ...           ...                 ...          ...   
3258         0           0             0                   0            0   
3259         0           0             0                   0            0   
3260         0           0             0                   0            0   
3261         0           0             0                   0            0   
3262         0           0             0                   0            0   

     kw_annihilated kw_annihilation kw_apocalypse kw_armageddon kw_army  ...  \
0                 0               0             0             0       0  ...   
1                 0               0             0             0       0  ...   
2                 0               0             0             0       0  ...   
3                 0               0             0             0       0  ...   
4                 0               0             0             0       0  ...   
...             ...             ...           ...           ...     ...  ...   
3258              0               0             0             0       0  ...   
3259              0               0             0             0       0  ...   
3260              0               0             0             0       0  ...   
3261              0               0             0             0       0  ...   
3262              0               0             0             0       0  ...   

     york young youth youtub yr zone ‰û ‰ûïwhen ‰ûò ‰ûó  
0       0     0     0      0  0    0  0       0   0   0  
1       0     0     0      0  0    0  0       0   0   0  
2       0     0     0      0  0    0  0       0   0   0  
3       0     0     0      0  0    0  0       0   0   0  
4       0     0     0      0  0    0  0       0   0   0  
...   ...   ...   ...    ... ..  ... ..     ...  ..  ..  
3258    0     0     0      0  0    0  0       0   1   0  
3259    0     0     0      0  0    0  0       0   0   0  
3260    0     0     0      0  0    0  0       0   0   0  
3261    0     0     0      0  0    0  0       0   0   0  
3262    0     0     0      0  0    0  0       0   0   0  

[3263 rows x 1830 columns]

In [37]:
DATA_FILE_BOW = os.path.join(DATA_DIR, "bowfinal10/test_bow.csv")

utils.dataframe_to_csv(test_df, DATA_FILE_BOW)